# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core_framework_api_pb2 as core__framework__api__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in core_framework_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreFrameworkAPIStub(object):
    """Service providing a standardized interface for sandboxes to interact with core framework services.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogFrameworkMessage = channel.unary_unary(
                '/coreframeworkapi.CoreFrameworkAPI/LogFrameworkMessage',
                request_serializer=core__framework__api__pb2.LogFrameworkMessageRequest.SerializeToString,
                response_deserializer=core__framework__api__pb2.LogFrameworkMessageResponse.FromString,
                _registered_method=True)
        self.RecordMetric = channel.unary_unary(
                '/coreframeworkapi.CoreFrameworkAPI/RecordMetric',
                request_serializer=core__framework__api__pb2.RecordMetricRequest.SerializeToString,
                response_deserializer=core__framework__api__pb2.RecordMetricResponse.FromString,
                _registered_method=True)
        self.GetConfigValue = channel.unary_unary(
                '/coreframeworkapi.CoreFrameworkAPI/GetConfigValue',
                request_serializer=core__framework__api__pb2.GetConfigValueRequest.SerializeToString,
                response_deserializer=core__framework__api__pb2.GetConfigValueResponse.FromString,
                _registered_method=True)


class CoreFrameworkAPIServicer(object):
    """Service providing a standardized interface for sandboxes to interact with core framework services.
    """

    def LogFrameworkMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreFrameworkAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogFrameworkMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.LogFrameworkMessage,
                    request_deserializer=core__framework__api__pb2.LogFrameworkMessageRequest.FromString,
                    response_serializer=core__framework__api__pb2.LogFrameworkMessageResponse.SerializeToString,
            ),
            'RecordMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMetric,
                    request_deserializer=core__framework__api__pb2.RecordMetricRequest.FromString,
                    response_serializer=core__framework__api__pb2.RecordMetricResponse.SerializeToString,
            ),
            'GetConfigValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigValue,
                    request_deserializer=core__framework__api__pb2.GetConfigValueRequest.FromString,
                    response_serializer=core__framework__api__pb2.GetConfigValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coreframeworkapi.CoreFrameworkAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coreframeworkapi.CoreFrameworkAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreFrameworkAPI(object):
    """Service providing a standardized interface for sandboxes to interact with core framework services.
    """

    @staticmethod
    def LogFrameworkMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreframeworkapi.CoreFrameworkAPI/LogFrameworkMessage',
            core__framework__api__pb2.LogFrameworkMessageRequest.SerializeToString,
            core__framework__api__pb2.LogFrameworkMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreframeworkapi.CoreFrameworkAPI/RecordMetric',
            core__framework__api__pb2.RecordMetricRequest.SerializeToString,
            core__framework__api__pb2.RecordMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coreframeworkapi.CoreFrameworkAPI/GetConfigValue',
            core__framework__api__pb2.GetConfigValueRequest.SerializeToString,
            core__framework__api__pb2.GetConfigValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
