name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - 'core/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - 'core/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Use Python 3.10 as specified in pyproject.toml

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run Linters
      run: |
        echo "Running Flake8 linter..."
        poetry run flake8 backend core tests
        echo "Flake8 linter passed."

    - name: Run Tests
      run: |
        echo "Running Pytest tests..."
        poetry run pytest tests/backend
        echo "Pytest tests passed."

    # TODO: Add steps for building Docker images, etc. if needed for CI (Issue #XX)
